[package]
name = "rulox-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
"rulox" = { path = "./rulox" }
"tokio" = { version = "1", features = ["rt", "macros", "time"] }

[workspace]
members = ["rulox", "rulox_macro", "rulox_types"]

[workspace.package]
authors = ["Caleb Robson"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Spartan2909/rulox"
