[package]
name = "rulox-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
"rulox" = { path = "./rulox" }
"rulox_types" = { path = "./rulox_types" }

[workspace]
members = ["rulox", "rulox_types"]

[workspace.package]
authors = ["Caleb Robson"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Spartan2909/rulox"
