[package]
name = "rulox"
version = "0.1.0"
edition = "2021"
description = "Helper types for the rulox crate."

authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"rulox_types" = { path = "../rulox_types" }

[lib]
proc-macro = true
