[package]
name = "rulox"
version = "0.4.0"
edition = "2021"
description = "A lightweight scripting language embedded in Rust."
documentation = "https://docs.rs/rulox/latest"

keywords = ["lox", "scripting", "parsing"]
categories = ["parser-implementations"]

repository.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"rulox_macro" = { path = "../rulox_macro", version = "0.4" }
"rulox_types" = { path ="../rulox_types", version = "0.1" }
