name: CI
on:
  push:
    branches: [ main ]
    paths-ignore: [ "**.md" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Rust
        run: rustup update

      - name: Build
        run: cargo build --workspace --verbose

      - name: Test
        run: cargo test --workspace --verbose
      
      - name: Run Clippy
        run: cargo clippy --workspace --verbose -- -Dwarnings
